name: logger
description: Dart package which implements log management for app.
version: 1.0.0
publish_to: none # Disallow publishing to pub.dev

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter_logs: ^2.2.1
  path_provider: ^2.0.8